### ISSUE TITLE
SAXS restraint error

### ISSUE THREAD

**Issue by CRA-Murray** [salilab/imp#1035]
When attempting to add a IMP.pmi.restraints.saxs.SAXSRestraint() to my system I received this error when upon execution of replica exchange:

```
Traceback (most recent call last):
  File "minimal.py", line 56, in <module>
    rex.execute_macro()
  File "/usr/local/lib/python3.8/site-packages/IMP/pmi/macros.py", line 395, in execute_macro
    output.init_stat2(low_temp_stat_file,
  File "/usr/local/lib/python3.8/site-packages/IMP/pmi/output.py", line 820, in init_stat2
    d = l.get_output()
  File "/usr/local/lib/python3.8/site-packages/IMP/pmi/restraints/__init__.py", line 107, in get_output
    score = self.evaluate()
  File "/usr/local/lib/python3.8/site-packages/IMP/pmi/restraints/__init__.py", line 83, in evaluate
    return self.weight * self.rs.unprotected_evaluate(None)
  File "/usr/local/lib/python3.8/site-packages/IMP/__init__.py", line 3785, in unprotected_evaluate
    return _IMP_kernel.RestraintSet_unprotected_evaluate(self, da)
_IMP_kernel.IOException: Profile  is not sampled for q = 0, q_max = 0.5
You can remove points with q > 0.5 from the experimental profile or recompute the profile with higher max_q
```

In the constructor for the SAXS restraint I set q_max to be 0.3 so this shouldn't be a problem. Below is a minimal python3 script that reproduces the error and I have attached a gz file with a pbd file and sample saxs .dat file so it will run.
[minimal.tar.gz](https://github.com/salilab/imp/files/5426367/minimal.tar.gz)

```python
import IMP
import IMP.saxs
import IMP.pmi
import IMP.pmi.topology
import IMP.pmi.dof
import IMP.pmi.macros
import IMP.pmi.restraints
import IMP.pmi.restraints.stereochemistry
import IMP.pmi.restraints.saxs
import sys
pdb = 'pnkp.pdb'
saxs_data = 'smooth.dat'


model = IMP.Model()
system = IMP.pmi.topology.System(model)
state = system.create_state()
dof_obj = IMP.pmi.dof.DegreesOfFreedom(model)


pnkp = state.create_molecule("PNKP", "LGSRGRLWLQSPTGGPPPIFLPSDGQALVLGRGPLTQVTDRKCSRNQVELIADPESRTVAVKQLGVNPSTVGVHELKPGLSGSLSLGDVLYLVNGLYPLTLRWEELSTSGSQPDAPPDTPGDPEEGEDTEPQKKRVRKSSLGWESLKKLLVFTASGVKPQGKVAAFDLDGTLITTRSGKVFPTSPSDWRILYPEIPKKLQELAAEGYKLVIFTNQMGIGRGKLPAEVFKGKVEAVLEKLGVPFQVLVATHAGLNRKPVSGMWDHLQEQANEGIPISVEDSVFVGDAAGRLANWAPGRKKKDFSCADRLFALNVGLPFATPEEFFLKWPAARFELPAFDPRTISSAGPLYLPESSSLLSPNPEVVVAVGFPGAGKSTFIQEHLVSAGYVHVNRDTLGSWQRCVSSCQAALRQGKRVVIDNTNPDVPSRARYIQCAKDAGVPCRCFNFCATIEQARHNNRFREMTDPSHAPVSDMVMFSYRKQFEPPTLAEGFLEILEIPFRLQEHLDPALQRLYRQFSEG", "D")

pnkp.add_structure(pdb, 'D', soft_check=True)

pnkp.add_representation(resolutions=0, color='medium purple')

#build molecules?
root_hierarchy = system.build()

dof_obj.create_rigid_body(pnkp)

###################### RESTRAINTS #####################
output_objects = [] # keep a list of functions that need to be reported

# SAXS restraint
sr = IMP.pmi.restraints.saxs.SAXSRestraint(root_hierarchy, saxs_data, maxq=0.3)
output_objects.append(sr)
IMP.pmi.tools.add_restraint_to_model(model, sr.rs)

dof_obj.optimize_flexible_beads(100)

# Run replica exchange Monte Carlo sampling
rex=IMP.pmi.macros.ReplicaExchange0(model,
                                    root_hier=root_hierarchy,                          
                                    #rmf_output_objects=crs,                     
                                    monte_carlo_sample_objects=dof_obj.get_movers(),  
                                    global_output_directory='output/',
                                    output_objects=output_objects,
                                    num_sample_rounds=1,
                                    monte_carlo_steps=50,
                                    number_of_frames=31,
                                    nframes_write_coordinates=2)                   
rex.execute_macro()
```

**Comment by benmwebb** [comment]
Thanks - I can reproduce this, and will investigate.

**Comment by benmwebb** [comment]
Yes, this looks like a bug with the restraint's handling of rigid bodies. Should be a simple fix but it would require recompilation.

**Comment by CRA-Murray** [comment]
Hi is this fix part of the release yet? I have updated my IMP and rebuilt from source a couple times but I am still getting this error. I have also done some additional testing with no rigid bodies and the same error appears. Does this have to do with the switch from python 3.8 to 3.9?

**Comment by benmwebb** [comment]
No, it is in git. You'll need to use a [nightly build](https://integrativemodeling.org/download.html#develop) or [build from the latest source code](https://integrativemodeling.org/nightly/doc/manual/installation.html#installation_download) at GitHub, develop branch.
