### ISSUE TITLE
ImportError with Mac OS 10.15.5

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#1039]
Hello, I get this error while simply attempting an `import IMP` line, eg:

```
MyMac/test:../../../../imp-20201201/imp-release/setup_environment.sh python test_xyzr.py 
Traceback (most recent call last):
  File "test_xyzr.py", line 2, in <module>
    import IMP
  File "/Users/riccardopellarin/imp-project/imp-20201201/imp-release/lib/IMP/__init__.py", line 15, in <module>
    import _IMP_kernel
ImportError: dlopen(/Users/riccardopellarin/imp-project/imp-20201201/imp-release/lib/_IMP_kernel.so, 2): Symbol not found: _PyBytes_AsString
  Referenced from: /Users/riccardopellarin/imp-project/imp-20201201/imp-release/lib/_IMP_kernel.so
  Expected in: flat namespace
 in /Users/riccardopellarin/imp-project/imp-20201201/imp-release/lib/_IMP_kernel.so
```

IMP compiled without issues on Mac OS catalina.

**Comment by Pellarin** [comment]
symbolic link to the wrong python binary, sorry!
