### ISSUE TITLE
IMP/pmi returns type error during RB construction

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#1074]
```
import IMP; print(IMP.__version__)
develop-3c9d63925c
```

```
rpellarin@ibcp22-087:~/imp-project/imp-20220912/Alphafold-IMP/Dpb10$ ~/imp-project/imp-20220912/imp-release/setup_environment.sh python test.py 
ReplicaExchange: MPI was found. Using Parallel Replica Exchange
BuildSystem.add_state: setting up molecule 25S copy number 0
BuildSystem.add_state: molecule 25S sequence has 2481 residues
BuildSystem.add_state: ---- setting up domain 0 of molecule 25S
BuildSystem.add_state: -------- domain 0 of molecule 25S extends from residue 1 to residue 2481 
BuildSystem.add_state: -------- domain 0 of molecule 25S represented by pdb file ./data/pre_60S_model.pdb 
BuildSystem.add_state: State 1 added
BuildSystem.execute_macro: building representations
done building "25S" Chain A Copy: 0
BuildSystem.execute_macro: setting up degrees of freedom
BuildSystem.execute_macro: -------- building rigid body ['25S..0']
BuildSystem.execute_macro: -------- adding 25S..0
BuildSystem.execute_macro: -------- creating rigid body with max_trans 4.0 max_rot 0.3 non_rigid_max_trans 4.0
Traceback (most recent call last):
  File "/home/rpellarin/imp-project/imp-20220912/Alphafold-IMP/Dpb10/test.py", line 73, in <module>
    root_hier, dof = bs.execute_macro(max_rb_trans=4.0, 
  File "/home/rpellarin/imp-project/imp-20220912/imp-release/lib/IMP/pmi/macros.py", line 825, in execute_macro
    self.dof.create_rigid_body(all_res,
  File "/home/rpellarin/imp-project/imp-20220912/imp-release/lib/IMP/pmi/dof/__init__.py", line 191, in create_rigid_body
    rb.set_is_rigid_member(p.get_index(), False)
  File "/home/rpellarin/imp-project/imp-20220912/imp-release/lib/IMP/core/__init__.py", line 6934, in set_is_rigid_member
    return _IMP_core.RigidBody_set_is_rigid_member(self, pi, tf)
TypeError: Wrong type in 'RigidBody_set_is_rigid_member', argument 2 of type 'IMP::ParticleIndex'
```

**Comment by NAKHDOAJALAL** [comment]
sorry i have some issue with this error i cant fix it for like a day and it takes so many time pls help me .

No module named 'imp'
  File "C:\Users\admin\Desktop\Telegrambotصفر تا صد\python\bot.py", line 1, in <module>
    from telegram.ext import Updater
ModuleNotFoundError: No module named 'imp'

What should i do with this imp i cant install it . should i install it or not ?

**Comment by benmwebb** [comment]
> No module named 'imp'

@NAKHDOAJALAL Please don't hijack unrelated issues.

If you are really trying to find Python's built-in imp module, you are in the wrong place. This is `IMP`. The `imp` package was removed from Python in Python 3.12: https://docs.python.org/3/whatsnew/3.12.html. Either contact the authors of your package and have them update it, or use an older version of Python.

**Comment by NAKHDOAJALAL** [comment]
Thank you
