### ISSUE TITLE
create_gmm.py error in imp2.20 python 10

### ISSUE THREAD

**Issue by grandrea** [salilab/imp#1093]
Hello,

I am seeing this new error when coarse graining a density with create_gmm.py

```
sampling points
fitting gmm
creating GMM with n_components 350 n_iter 100 covar type full
fitting
Traceback (most recent call last):
  File "/home/miniconda3/envs/imp-220/lib/python3.10/site-packages/IMP/isd/create_gmm.py", line 159, in <module>
    main()
  File "/home/miniconda3/envs/imp-220/lib/python3.10/site-packages/IMP/isd/create_gmm.py", line 155, in main
    run(args)
  File "/home/miniconda3/envs/imp-220/lib/python3.10/site-packages/IMP/isd/create_gmm.py", line 117, in run
    IMP.isd.gmm_tools.fit_gmm_to_points(
  File "/home/miniconda3/envs/imp-220/lib/python3.10/site-packages/IMP/isd/gmm_tools.py", line 335, in fit_gmm_to_points
    model = gmm.fit(points)
  File "/home/miniconda3/envs/imp-220/lib/python3.10/site-packages/sklearn/mixture/_base.py", line 181, in fit
    self.fit_predict(X, y)
  File "/home/miniconda3/envs/imp-220/lib/python3.10/site-packages/sklearn/base.py", line 1351, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/miniconda3/envs/imp-220/lib/python3.10/site-packages/sklearn/mixture/_base.py", line 214, in fit_predict
    raise ValueError(
ValueError: Expected n_samples >= n_components but got n_components = 350, n_samples = 262

```

any clues how to proceed?

**Comment by grandrea** [comment]
```
name: imp-220
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.10=hd590300_0
  - aom=3.7.1=h59595ed_0
  - attr=2.5.1=h166bdaf_1
  - blas=1.0=openblas
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.25.0=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - contourpy=1.2.0=py310hd41b1e2_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cython=3.0.7=py310hc6cd4ac_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=6.1.1=gpl_hf3b701a_101
  - fftw=3.3.10=nompi_hc118613_108
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.47.2=py310h2372a71_0
  - freeglut=3.2.2=hac7e632_2
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gettext=0.21.1=h27087fc_0
  - glib=2.78.3=hfc55251_0
  - glib-tools=2.78.3=hfc55251_0
  - gmp=6.3.0=h59595ed_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.22.8=h8e1006c_1
  - gstreamer=1.22.8=h98fc4e7_1
  - harfbuzz=8.3.0=h3d44ed6_0
  - hdbscan=0.8.33=py310h1f7b6fc_4
  - hdf5=1.14.3=nompi_h4f84152_100
  - icu=73.2=h59595ed_0
  - ihm=0.43=py310h2372a71_0
  - imp=2.20.1=py310hab4dabd_1
  - jasper=4.1.2=he6dfbbe_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.2=h59595ed_1
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=21_linux64_openblas
  - libboost=1.82.0=h6fcfa73_6
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=21_linux64_openblas
  - libclang=15.0.7=default_hb11cfb5_4
  - libclang13=15.0.7=default_ha2b6cf4_4
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.5.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgcrypt=1.10.3=hd590300_0
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libglib=2.78.3=h783c2da_0
  - libglu=9.0.0=hac7e632_1003
  - libgomp=13.2.0=h807b86a_3
  - libgpg-error=1.47=h71f35ed_0
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=21_linux64_openblas
  - liblapacke=3.9.0=21_linux64_openblas
  - libllvm15=15.0.7=hb3ce162_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libopencv=4.9.0=py38h6bf8061_6
  - libopenvino=2023.2.0=h2e90f83_5
  - libopenvino-auto-batch-plugin=2023.2.0=hd5fc58b_5
  - libopenvino-auto-plugin=2023.2.0=hd5fc58b_5
  - libopenvino-hetero-plugin=2023.2.0=h3ecfda7_5
  - libopenvino-intel-cpu-plugin=2023.2.0=h2e90f83_5
  - libopenvino-intel-gpu-plugin=2023.2.0=h2e90f83_5
  - libopenvino-ir-frontend=2023.2.0=h3ecfda7_5
  - libopenvino-onnx-frontend=2023.2.0=hfbc7f12_5
  - libopenvino-paddle-frontend=2023.2.0=hfbc7f12_5
  - libopenvino-pytorch-frontend=2023.2.0=h59595ed_5
  - libopenvino-tensorflow-frontend=2023.2.0=h0bff32c_5
  - libopenvino-tensorflow-lite-frontend=2023.2.0=h59595ed_5
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h753d276_0
  - libpq=16.1=h33b98f1_7
  - libprotobuf=4.25.1=hf27288f_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libsystemd0=255=h3516f8a_0
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.6.0=ha9c0a0a_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.20.0=hd590300_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h59595ed_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.6.0=hd429924_1
  - libxml2=2.12.4=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib=3.8.2=py310hff52083_0
  - matplotlib-base=3.8.2=py310h62c0568_0
  - mpfr=4.2.1=h9458935_0
  - mpg123=1.32.4=h59595ed_0
  - mpi=1.0=mpich
  - mpich=4.1.2=h846660c_101
  - msgpack-python=1.0.7=py310hd41b1e2_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncurses=6.4=h6a678d5_0
  - nettle=3.9.1=h7ab15ed_0
  - nspr=4.35=h27087fc_0
  - nss=3.97=h1d7d5a4_0
  - numexpr=2.8.7=py310h286c3b5_0
  - numpy=1.26.3=py310hb13e2d6_0
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openh264=2.4.0=h59595ed_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=3.2.0=hd590300_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.4=py310h1128e8f_0
  - pcre2=10.42=hcad00b1_0
  - pillow=10.2.0=py310h01dd4db_0
  - pip=23.3.1=py310h06a4308_0
  - pixman=0.43.0=h59595ed_0
  - ply=3.11=py_1
  - protobuf=4.25.1=py310h620c231_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=16.1=hb77b528_5
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - pyrmsd=4.3.2=py310hcc13569_2
  - python=3.10.12=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=4_cp310
  - pytz=2023.3.post1=py310h06a4308_0
  - qt-main=5.15.8=h450f30e_18
  - readline=8.2=h5eee18b_0
  - rmf=1.6.0=py310h3150b46_0
  - scikit-learn=1.4.0=py310h1fdf081_0
  - scipy=1.11.4=py310heeff2f4_0
  - setuptools=68.2.2=py310h06a4308_0
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - sqlite=3.41.2=h5eee18b_0
  - svt-av1=1.8.0=h59595ed_0
  - tbb=2021.11.0=h00ab1b0_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.3=py310h2372a71_1
  - tzdata=2023d=h04d1e81_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - wheel=0.41.2=py310h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.40=hd590300_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
```

**Comment by grandrea** [comment]
I see the -n flag with num samples
