### ISSUE TITLE
python restraint returns error upon evaluation

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#888]
Hi, I got stuck into this problem. I wanted to write a restraint in python. However, when I evaluate it, i got the following error:

```
Traceback (most recent call last):
  File "test.py", line 80, in test_2
    sf.evaluate(False)
  File "/Users/riccardopellarin/imp-project/imp-130215/imp-fast/lib/IMP/kernel/__init__.py", line 2779, in evaluate
    return _IMP_kernel.ScoringFunction_evaluate(self, *args)
ValueException: Argument not of correct type
```

It looks like it is related to the `do_get_inputs` function. If this function returns an empty list, the evaluation is OK, otherwise if it returns the particles stored in the restraint class, I get the error above.
Here's a test that one can run to reproduce the error.

```
import IMP
import IMP.atom
import IMP.test

class TestRestraint(IMP.kernel.Restraint):

        def __init__(self,m):
            IMP.kernel.Restraint.__init__(self, m, "TestRestraint %1%")
            self.particles=[]
            
        def unprotected_evaluate(self,da):
            return -1

        def add_particles(self,particles):
            self.particles+=particles
            
        def do_get_inputs(self):
            return self.particles



def add_component_beads(m,protein_h,name,ds):
    from math import pi
    for n, dss in enumerate(ds):
        ds_frag = (dss[0], dss[1])
        prt = IMP.Particle(m)
        h = IMP.atom.Fragment.setup_particle(prt)
        h.set_name(name + '_%i-%i_bead' % (ds_frag[0], ds_frag[1]))
        prt.set_name(name + '_%i-%i_bead' % (ds_frag[0], ds_frag[1]))
        h.set_residue_indexes(list(range(ds_frag[0], ds_frag[1] + 1)))
        root = IMP.atom.Hierarchy.setup_particle(IMP.Particle(m))
        root.set_name("Beads")
        protein_h.add_child(root)
        root.add_child(h)
        IMP.core.XYZR.setup_particle(prt)
        ptem = IMP.core.XYZR(prt)
        mass = IMP.atom.get_mass_from_number_of_residues(len(h.get_residue_indexes()))
        volume = IMP.atom.get_volume_from_mass(mass)
        radius = 0.8 * (3.0 / 4.0 / pi * volume) ** (1.0 / 3.0)
        IMP.atom.Mass.setup_particle(prt, mass)
        ptem.set_radius(radius)
        IMP.core.XYZ(prt).set_coordinates_are_optimized(True)

def create_component(m,name):
    protein_h = IMP.atom.Molecule.setup_particle(IMP.Particle(m))
    protein_h.set_name(name)
    return protein_h

class TestPythonRestraint(IMP.test.TestCase):
    def test_1(self):
        '''
        This test does not fail
        '''
        m=IMP.Model()

        #create a bead
        hierarchy=create_component(m,"Test")
        add_component_beads(m,hierarchy,"Test",[(1,10)])
        
        #check the restraint
        r=TestRestraint(m)
        sf=r.create_scoring_function()
        sf.evaluate(False)

    def test_2(self):
        '''
        This test fails
        '''
        m=IMP.Model()
        
        #create a bead
        hierarchy=create_component(m,"Test")
        add_component_beads(m,hierarchy,"Test",[(1,10)])

        #check the restraint
        r=TestRestraint(m)
        ps=IMP.atom.get_leaves(hierarchy)
        r.add_particles(ps)
        sf=r.create_scoring_function()
        sf.evaluate(False)



if __name__ == '__main__':
    IMP.test.main()
```

**Comment by Pellarin** [comment]
Ok, I probably got the problem. `ps=IMP.atom.get_leaves(hierarchy)` return Hierarchies and not particles. If one substitutes the `test_2` with the following

```
    def test_2(self):
        '''
        This test fails
        '''
        m=IMP.Model()
        
        #create a bead
        hierarchy=create_component(m,"Test")
        add_component_beads(m,hierarchy,"Test",[(1,10)])

        #check the restraint
        r=TestRestraint(m)
        ps=[p.get_particle() for p in IMP.atom.get_leaves(hierarchy)]
        r.add_particles(ps)
        sf=r.create_scoring_function()
        sf.evaluate(False)
```

all tests pass. But now, isn't it a weird error message?

**Comment by benmwebb** [comment]
Yes, looks like lazy code on Daniel's part here. Shouldn't be too hard to have it print something about the type it got and the type it wants.
