### ISSUE TITLE
IMP.core.transform error

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#913]
Can somebody explain me why I get this error?

```
<class 'IMP.Particle'>
<class 'IMP.algebra.Transformation3D'> 1 0 0 0 || (-90.238, 14.8042, 52.0534)
Traceback (most recent call last):
  File "modeling.py", line 186, in <module>
    bounding_box=[(-100,-100,-100),(100,100,100)])
  File "/Users/riccardopellarin/imp-project/imp-080915/imp-debug/lib/IMP/pmi/representation.py", line 1207, in shuffle_configuration
    IMP.core.transform(d, transformation)
  File "/Users/riccardopellarin/imp-project/imp-080915/imp-debug/lib/IMP/core/__init__.py", line 5909, in transform
    return _IMP_core.transform(*args)
_IMP_kernel.UsageException: Usage check failure: Python is calling the wrong function

```
here's the code that generated it, as you can see the types are OK
```
                print(type(fb))
                print(type(transformation),transformation)
                d=IMP.core.XYZ(fb)
                IMP.core.transform(d, transformation)
```

**Comment by benmwebb** [comment]
You'll get this error if `fb` is also a `RigidBody`, in which case you should instead do

    d = IMP.core.RigidBody(fb)
    IMP.core.transform(d, transformation)

**Comment by Pellarin** [comment]
Thanks, unfortunately that does not look like the issue. Running:

```
                if IMP.core.NonRigidMember.get_is_setup(fb) or IMP.core.RigidMember.get_is_setup(fb):
                    d=IMP.core.RigidBody(fb)
                else: 
                    d=IMP.core.XYZ(fb)
                print(type(d),d,fb)  
                IMP.core.transform(d, transformation)
```

I still get

```
<class 'IMP.core.XYZ'> (0, 0, 0) "TssJ_A..0_1-20_bead_floppy_body"
Traceback (most recent call last):
  File "modeling.py", line 186, in <module>
    bounding_box=[(-100,-100,-100),(100,100,100)])
  File "/Users/riccardopellarin/imp-project/imp-080915/imp-debug/lib/IMP/pmi/representation.py", line 1209, in shuffle_configuration
    IMP.core.transform(d, transformation)
  File "/Users/riccardopellarin/imp-project/imp-080915/imp-debug/lib/IMP/core/__init__.py", line 5909, in transform
    return _IMP_core.transform(*args)
_IMP_kernel.UsageException: Usage check failure: Python is calling the wrong function
```

**Comment by benmwebb** [comment]
Right, because a `RigidBody` isn't necessarily also a `RigidMember`. Why didn't you try the code I suggested?

**Comment by Pellarin** [comment]
yes, that is the result:

```
  File "modeling.py", line 186, in <module>
    bounding_box=[(-100,-100,-100),(100,100,100)])
  File "/Users/riccardopellarin/imp-project/imp-080915/imp-debug/lib/IMP/pmi/representation.py", line 1204, in shuffle_configuration
    d=IMP.core.RigidBody(fb)
  File "/Users/riccardopellarin/imp-project/imp-080915/imp-debug/lib/IMP/core/__init__.py", line 5014, in __init__
    this = _IMP_core.new_RigidBody(*args)
_IMP_kernel.InternalException: Internal check failure: Particle TssM_A..0_1-12_bead_floppy_body missing required attributes for decorator RigidBody
  File "include/IMP/core/rigid_bodies.h", line 147
```

**Comment by benmwebb** [comment]
OK, well `TssM` isn't a rigid body. But `TssJ` is. I can only help you with the code you've shown me ;) It looks like you're trying to plug this into a much bigger piece of code which I can't see. You can protect it with a `get_is_setup` call as you did above, just for `RigidBody` rather than `RigidMember`.

**Comment by Pellarin** [comment]
`> I can only help you with the code you've shown me ;) It looks like you're trying to plug this into a much bigger piece of code which I can't see.`

Sure! Thanks, your suggestion, using `get_is_setup` for `RigidBody`, worked!
