### ISSUE TITLE
swig undefined object but everything looks regular to me

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#925]
I wanted to create a base ISDRestraint class for ISD restraints, so that I have a get_probability() method exposed and usable, for instance, by the IMP.isd.LogWrapper(). Here's the code of include/ISDRestraint.h (no cpp file associated...):

```
/**
 *  \file IMP/isd/ISDRestraint.h
 *
 *  Copyright 2007-2016 IMP Inventors. All rights reserved.
 *
 */

#ifndef IMPISD_ISD_RESTRAINT_H
#define IMPISD_ISD_RESTRAINT_H
#include "isd_config.h"
#include <IMP/Restraint.h>

IMPISD_BEGIN_NAMESPACE
/** A base class for ISD Restraints.
 */

class IMPISDEXPORT ISDRestraint : public Restraint {

 public:
  //! Create the restraint.
  /** Restraints should store the particles they are to act on,
      preferably in a Singleton or PairContainer as appropriate.
   */

ISDRestraint(IMP::Model *m)
    : Restraint(m, "ISDRestraint%1%") {} 

    virtual double get_probability() const;

    virtual double unprotected_evaluate(IMP::DerivativeAccumulator *accum)
      const IMP_OVERRIDE;
    virtual IMP::ModelObjectsTemp do_get_inputs() const IMP_OVERRIDE;
    IMP_OBJECT_METHODS(ISDRestraint);
};

IMPISD_END_NAMESPACE

#endif /* IMPISD_ISD_RESTRAINT_H */
```

Changed the swig file accordingly and wrote a test:

```
#!/usr/bin/env python

# imp general
import IMP
import IMP.core
import IMP.isd

# unit testing framework
import IMP.test

class ISDRestraint(IMP.isd.ISDRestraint):
    def __init__(self,m):
        IMP.isd.ISDRestraint.__init__(self, m, "ISDRestraint %1%")


class TestISDRestraint(IMP.test.TestCase):

    def test_setup(self):
        m=IMP.Model()
        isdr=ISDRestraint(m)       
        print(dir(isdr))

if __name__ == '__main__':
    IMP.test.main()
```

Everything compiles (from scratch) in debug mode, but I get this error when I run the test:

```
[rpellari@liberte test]$ ~/imp-projects/imp-130116/imp-debug/setup_environment.sh python test_ISDRestraint.py
Traceback (most recent call last):
  File "test_ISDRestraint.py", line 6, in <module>
    import IMP.isd
  File "/Bis/home/rpellari/imp-projects/imp-130116/imp-debug/lib/IMP/isd/__init__.py", line 30, in <module>
    _IMP_isd = swig_import_helper()
  File "/Bis/home/rpellari/imp-projects/imp-130116/imp-debug/lib/IMP/isd/__init__.py", line 22, in swig_import_helper
    import _IMP_isd
ImportError: /Bis/home/rpellari/imp-projects/imp-130116/imp-debug/lib/_IMP_isd.so: undefined symbol: _ZTIN3IMP3isd12ISDRestraintE
```

**Comment by benmwebb** [comment]
You have declared an abstract base class (no implementations for the `virtual` methods), so you can't instantiate it (by design). You can't instantiate `IMP::Restraint` either.

BTW, it's redundant to call it `isd::ISDRestraint`. Just call it `isd::Restraint`. See `saxs::Restraint` for an example.
