### ISSUE TITLE
Problem linking hierarchies in clustering

### ISSUE THREAD

**Issue by iecheverria** [salilab/imp#945]
In the new version of the analysis macro, after reading the coordinates from the rmfs,  the hierarchies are not linked properly resulting in an error. This seems like a bug, but I'm not sure where. 

The current error is:

> linking hierarchies for frame 1139 rmf file 
output//rmfs//0.rmf3
Linking reps Frag_262-275 and Frag_262-275: Res 10
Traceback (most recent call last):
  File "clustering.py", line 55, in <module>
    distance_matrix_file='kmeans_'+str(nclusters))
  File "/bell1/home/ignacia/SOFTW/imp-fast/lib/IMP/pmi/macros.py", line 1549, in clustering
    state_number=state_number)
  File "/bell1/home/ignacia/SOFTW/imp-fast/lib/IMP/pmi/io/__init__.py", line 385, in read_coordinates_of_rmfs
    IMP.pmi.analysis.link_hiers_to_rmf(model,prots,frame_number,rmf_file)
  File "/bell1/home/ignacia/SOFTW/imp-fast/lib/IMP/pmi/analysis.py", line 1433, in link_hiers_to_rmf
    IMP.rmf.link_hierarchies(rh, hiers)
  File "/bell1/home/ignacia/SOFTW/imp-fast/lib/IMP/rmf/__init__.py", line 708, in link_hierarchies
    return _IMP_rmf.link_hierarchies(fh, hs)
RuntimeError: UsageError: "Collision on association keys."

**Comment by cgreenberg** [comment]
My fault, I didn't realize a change in Representation would lead to RMF problems. I will check in a fix, let me know if that works.

**Comment by iecheverria** [comment]
Is working now. Thanks!
