### ISSUE TITLE
Rasterizing error in gmm_tools.write_gmm_to_map()

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#948]
both in fast or slow mode

```
...
done EM setup
will write GMM map to initial.composite-map.250.mrc
rasterizing
creating map
Grid <class 'IMP.algebra.DenseDoubleGrid3D'>
Traceback (most recent call last):
  File "modeling_pmi2_table.py", line 233, in <module>
    gem.target_ps, "initial.composite-map.250.mrc", 10, fast=False)
  File "/Users/riccardopellarin/imp-project/imp-060516/imp-fast/lib/IMP/isd/gmm_tools.py", line 110, in write_gmm_to_map
    d1=IMP.em.create_density_map(grid)
  File "/Users/riccardopellarin/imp-project/imp-060516/imp-fast/lib/IMP/em/__init__.py", line 990, in create_density_map
    return _IMP_em.create_density_map(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'create_density_map'.
  Possible C/C++ prototypes are:
    IMP::em::create_density_map(IMP::em::DensityMap const *)
    IMP::em::create_density_map(IMP::algebra::BoundingBox3D const &,double)
    IMP::em::create_density_map(int,int,int,double)
    IMP::em::create_density_map(IMP::algebra::GridD< 3,IMP::algebra::DenseGridStorageD< 3,float >,float,IMP::algebra::DefaultEmbeddingD< 3 > > const &)
```

**Comment by cgreenberg** [comment]
The error you posted only occurs in fast mode. In debug we have this recurring error due, I think, to @shanot 's change to get_rasterized:

```
 File "/Users/cgreen/imp_debug/lib/IMP/algebra/__init__.py", line 8686, in get_rasterized
    return _IMP_algebra.get_rasterized(*args)
InternalException: Internal check failure: 


->>>>not proper matrix!!



  File "/Users/cgreen/imp/modules/algebra/src/Gaussian3D.cpp", line 89
```

**Comment by cgreenberg** [comment]
Oh. It's not so bad. It's just that when @shanot switched to using `IMP_INTERNAL_CHECK` he didn't flip the boolean logic. For the record, the `CHECK` expects the first part to evaluate to `true`.

I was wrong, though, there is also a problem with create_density_map from DensityGrid (aka  DenseGrid3D<double>)....

**Comment by cgreenberg** [comment]
It's fixed if we use `DenseGrid3D<float>` instead of  `DenseGrid3D<double>` but I have no idea why. @benmwebb  ?

**Comment by Pellarin** [comment]
Why I get the same error again?

```
Traceback (most recent call last):
  File "modeling_pmi2_table.py", line 252, in <module>
    gem.target_ps, "composite-map_region_larger_threshold.100.mrc", 2.5, fast=True)
  File "/Bis/home/rpellari/imp-projects/imp-100516/imp-fast/lib/IMP/isd/gmm_tools.py", line 113, in write_gmm_to_map
    d1 = gmm2map(to_draw,voxel_size,bounding_box,origin, fast)
  File "/Bis/home/rpellari/imp-projects/imp-100516/imp-fast/lib/IMP/isd/gmm_tools.py", line 107, in gmm2map
    d1=IMP.em.create_density_map(grid)
  File "/Bis/home/rpellari/imp-projects/imp-100516/imp-fast/lib/IMP/em/__init__.py", line 994, in create_density_map
    return _IMP_em.create_density_map(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'create_density_map'.
  Possible C/C++ prototypes are:
    IMP::em::create_density_map(IMP::em::DensityMap const *)
    IMP::em::create_density_map(IMP::algebra::BoundingBox3D const &,double)
    IMP::em::create_density_map(int,int,int,double)
    IMP::em::create_density_map(IMP::algebra::GridD< 3,IMP::algebra::DenseGridStorageD< 3,float >,float,IMP::algebra::DefaultEmbeddingD< 3 > > const &)
    IMP::em::create_density_map(IMP::algebra::GridD< 3,IMP::algebra::DenseGridStorageD< 3,double >,double,IMP::algebra::DefaultEmbeddingD< 3 > > const &)
```

**Comment by shanot** [comment]
It looks like python thinks the return value of get_rasterized is of type `IMP.algebra.DenseDoubleGrid3D`, which is python only.

**Comment by Pellarin** [comment]
Maybe it is a swig problem then?

**Comment by cgreenberg** [comment]
Does the isd/test/medium_test_gaussian_em_restraint.py also fail for you?

**Comment by Pellarin** [comment]
yes

```
MyMac/test:~/imp-project/imp-250216/imp-fast/setup_environment.sh python medium_test_gaussian_em_restraint.py 
E....E
======================================================================
ERROR: test_local_score (__main__.LocalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "medium_test_gaussian_em_restraint.py", line 201, in test_local_score
    update_model,backbone_slope,local)
  File "/Users/riccardopellarin/imp-project/imp-250216/imp-fast/lib/IMP/isd/__init__.py", line 3759, in __init__
    this = _IMP_isd.new_GaussianEMRestraint(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_GaussianEMRestraint'.
  Possible C/C++ prototypes are:
    IMP::isd::GaussianEMRestraint::GaussianEMRestraint(IMP::Model *,IMP::ParticleIndexes,IMP::ParticleIndexes,IMP::ParticleIndex,IMP::Float,IMP::Float,IMP::Float,bool,bool,std::string)
    IMP::isd::GaussianEMRestraint::GaussianEMRestraint(IMP::Model *,IMP::ParticleIndexes,IMP::ParticleIndexes,IMP::ParticleIndex,IMP::Float,IMP::Float,IMP::Float,bool,bool)
    IMP::isd::GaussianEMRestraint::GaussianEMRestraint(IMP::Model *,IMP::ParticleIndexes,IMP::ParticleIndexes,IMP::ParticleIndex,IMP::Float,IMP::Float,IMP::Float,bool)
    IMP::isd::GaussianEMRestraint::GaussianEMRestraint(IMP::Model *,IMP::ParticleIndexes,IMP::ParticleIndexes,IMP::ParticleIndex,IMP::Float,IMP::Float,IMP::Float)


======================================================================
ERROR: Test making a map from a GMM
----------------------------------------------------------------------
Traceback (most recent call last):
  File "medium_test_gaussian_em_restraint.py", line 176, in test_rasterize
    dmap = IMP.isd.gmm_tools.gmm2map(self.model_ps,1.0,fast=False)
AttributeError: 'module' object has no attribute 'gmm2map'

----------------------------------------------------------------------
Ran 6 tests in 0.831s

FAILED (errors=2)
```

**Comment by cgreenberg** [comment]
That doesn't make sense...........you may want to rebuild your IMP. That test is passing on all the test machines.

**Comment by Pellarin** [comment]
Ooops sorry, you're right!

**Comment by shanot** [comment]
on our system, as of 75a687c76ba7c2b2332d615c8782be5e48fbf272 this test still fails.

**Comment by Pellarin** [comment]
@shanot please see the last comment in #951, maybe I found a solution. Can you check it?

**Comment by benmwebb** [comment]
Also reported by @duhovka with Ubuntu 16.10. I reproduced the problem on both 16.10 and 16.04, but only when building IMP *without* CGAL (which is presumably what you are doing).  Our regular builds include CGAL which is why we weren't seeing this problem here. The two types aren't quite interchangeable in Python, but something in the CGAL wrappers is convincing SWIG to allow the conversion. Fix to follow.
